#!/usr/bin/env python3
"""Primary-source competitor completeness backfill for 2026 Test events."""
from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from datastore.research_fact_store import upsert_research_facts


GROUPS = [
    {
        "context_ticker": "CMPX",
        "subject": "CTX-8371 - NSCLC",
        "indication": "NSCLC",
        "comparator": "Datopotamab deruxtecan in TROPION-PanTumor01",
        "population": "Heavily pretreated advanced/metastatic NSCLC; 6 mg/kg cohort (N=50)",
        "as_of_date": "2023-06-23",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC10564307/",
        "source_kind": "peer_reviewed_publication",
        "orr": "26% (13/50; confirmed)",
        "cr": "0% (0/50; all confirmed responses were partial)",
        "pr": "26% (13/50; confirmed)",
        "median_pfs": "6.9 months (95% CI 2.7-8.8)",
        "median_os": "11.4 months (95% CI 7.1-20.6)",
        "safety": "Drug-related TEAE 82%; grade >=3 drug-related TEAE 26% at 6 mg/kg",
        "adverse_events": "Nausea; stomatitis; alopecia; adjudicated drug-related ILD/pneumonitis",
        "adverse_event_rates": "NSCLC cohort any-grade nausea 64%, stomatitis 60%, alopecia 42%; ILD/pneumonitis 6% at 6 mg/kg",
        "dose": "6 mg/kg IV once every 3 weeks",
        "price": "USD 4,988.74 WAC per 100 mg single-dose vial",
        "price_as_of": "2025-01-01",
        "price_source": "https://datrowayhcp.com/-/media/Project/Oncology/DATO-HCP/Other/PDF/DATROWAY-Connecticut-Pricing-Sheet-Digital.pdf",
        "price_metric": "actual_price",
        "price_status": "reported",
        "price_classification": "Market Data",
    },
    {
        "context_ticker": "CMPX",
        "subject": "CTX-8371 - TNBC",
        "indication": "mTNBC",
        "comparator": "Sacituzumab govitecan in ASCENT",
        "population": "Brain-metastasis-negative relapsed/refractory mTNBC; ASCENT efficacy population (N=235)",
        "as_of_date": "2021-04-22",
        "source_url": "https://www.tga.gov.au/sites/default/files/auspar-sacituzumab-govitecan-220329.pdf",
        "source_kind": "regulator_clinical_document",
        "orr": "35% (82/235; BICR)",
        "cr": "4% (10/235; BICR)",
        "pr": "31% (72/235; BICR)",
        "median_pfs": "5.6 months (95% CI 4.3-6.3; BM-negative primary efficacy population)",
        "median_os": "12.1 months (95% CI 10.7-14.0; BM-negative primary efficacy population)",
        "safety": "ASCENT: serious adverse reactions 27%; fatal adverse reactions 1.2%; permanent discontinuation 5%",
        "adverse_events": "Neutropenia; diarrhea; anemia; febrile neutropenia; pneumonia",
        "adverse_event_rates": "Grade >=3 neutropenia 52%, diarrhea 11%, anemia 8%, febrile neutropenia 6%",
        "dose": "10 mg/kg IV on days 1 and 8 of each 21-day cycle",
        "clinical_source_overrides": {
            "median_pfs": "https://pubmed.ncbi.nlm.nih.gov/33882206/",
            "median_os": "https://pubmed.ncbi.nlm.nih.gov/33882206/",
            "safety": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761115s059lbl.pdf",
            "adverse_events": "https://ascopubs.org/doi/10.1200/JCO.2022.40.16_suppl.1071",
            "adverse_event_rates": "https://ascopubs.org/doi/10.1200/JCO.2022.40.16_suppl.1071",
            "dose": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/761115s059lbl.pdf",
        },
        "price": "USD 20,918 WAC per 21-day cycle (two infusions; 72 kg at 10 mg/kg)",
        "price_as_of": "2026-01-01",
        "price_source": "https://www.gileadpriceinfo.com/trodelvy",
        "price_metric": "actual_price",
        "price_status": "reported",
        "price_classification": "Market Data",
    },
    {
        "context_ticker": "CMPX",
        "subject": "CTX-8371 - HL",
        "indication": "R/R classical Hodgkin lymphoma",
        "comparator": "Acimtamig plus AlloNK in LuminICE-203",
        "population": "Heavily pretreated R/R classical Hodgkin lymphoma; initial phase 2 evaluable cohort (N=10)",
        "as_of_date": "2024-07-24",
        "source_url": "https://ash.confex.com/ash/2024/webprogram/Paper193896.html",
        "source_kind": "conference_abstract",
        "orr": "90% (9/10; IRC)",
        "cr": "60% (6/10; IRC)",
        "pr": "30% (3/10; IRC)",
        "median_pfs": "Not reported in the initial LuminICE-203 conference abstract",
        "median_pfs_status": "unavailable",
        "median_os": "Not reported in the initial LuminICE-203 conference abstract",
        "median_os_status": "unavailable",
        "safety": "All patients had a TEAE; no related discontinuations, ICANS or GvHD",
        "adverse_events": "Infusion-related reactions; cytokine release syndrome",
        "adverse_event_rates": "Infusion-related reactions 60% (all grade 1/2); CRS 30%, including one grade 3 event (10%)",
        "dose": "Acimtamig 200 or 300 mg IV days 1, 8, 15, 22, 29 and 36; AlloNK 2-4 billion cells days 1, 8 and 15 per 48-day cycle",
        "price": "No actual or forecast price reported; combination remains investigational",
        "price_as_of": "2024-07-24",
        "price_source": "https://ash.confex.com/ash/2024/webprogram/Paper193896.html",
        "price_metric": "forecast_price",
        "price_status": "unavailable",
        "price_classification": "Analyst Assumption",
    },
    {
        "context_ticker": "MOLN",
        "subject": "MP0712 - SCLC",
        "indication": "Relapsed/refractory ES-SCLC",
        "comparator": "Tarlatamab in relapsed extensive-stage SCLC",
        "population": "DeLLphi-301 efficacy population at 10 mg (N=99)",
        "as_of_date": "2023-10-02",
        "source_url": "https://www.fda.gov/drugs/development-approval-process-drugs/drug-trials-snapshots-imdelltra",
        "source_kind": "regulator_clinical_document",
        "orr": "40% (40/99; BICR)",
        "cr": "2% (2/99; BICR)",
        "pr": "38% (38/99; BICR)",
        "median_pfs": "4.9 months (95% CI 2.9-6.7) at 10 mg",
        "median_os": "14.3 months (95% CI 10.8-not estimable) at 10 mg",
        "safety": "Pooled safety N=187: serious adverse reactions 58%, fatal adverse reactions 2.7%, permanent discontinuation 7%",
        "adverse_events": "Cytokine release syndrome; fatigue; neurologic toxicity including ICANS; anemia",
        "adverse_event_rates": "CRS 55% (grade 3/4 1.6%); fatigue 51% (grade 3/4 10%); neurologic toxicity 47% (grade 3 10%); ICANS 9%; anemia 27% (grade 3/4 6%)",
        "dose": "Cycle 1 day 1: 1 mg IV; cycle 1 day 8 onward: 10 mg IV; then every 2 weeks",
        "clinical_source_overrides": {
            "median_pfs": "https://www.nejm.org/doi/full/10.1056/NEJMoa2307980",
            "median_os": "https://pmc.ncbi.nlm.nih.gov/articles/PMC11929685/",
            "safety": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/761344s000lbl.pdf",
            "adverse_events": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/761344s000lbl.pdf",
            "adverse_event_rates": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/761344s000lbl.pdf",
            "dose": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/761344s000lbl.pdf",
        },
        "price": "USD 15,099.46 cash price per 10 mg vial",
        "price_as_of": "2026-07-18",
        "price_source": "https://www.drugs.com/price-guide/imdelltra",
        "price_metric": "actual_price",
        "price_status": "reported",
        "price_classification": "Market Data",
    },
    {
        "context_ticker": "MOLN",
        "subject": "MP0712 - EP-NEC",
        "indication": "DLL3-positive extrapulmonary NEC",
        "comparator": "Obrixtamig in DLL3-positive extrapulmonary neuroendocrine carcinoma",
        "population": "Regimens B2+B3, >=90 micrograms/kg; confirmed-response population (N=56)",
        "as_of_date": "2025-09-01",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12440289/",
        "source_kind": "peer_reviewed_publication",
        "orr": "19.6% confirmed (11/56)",
        "cr": "0% (0/56)",
        "pr": "19.6% confirmed (11/56)",
        "median_pfs": "Not reported for the epNEC efficacy population in the primary publication",
        "median_pfs_status": "unavailable",
        "median_os": "Not reported for the epNEC efficacy population in the primary publication",
        "median_os_status": "unavailable",
        "safety": "All-dose safety N=168: treatment-related AE 88%; grade >=3 treatment-related AE 24%; related discontinuation 4%",
        "adverse_events": "Cytokine release syndrome; dysgeusia; pyrexia; asthenia; decreased lymphocyte count; potential ICANS",
        "adverse_event_rates": "CRS 57%, dysgeusia 23%, pyrexia 21%, asthenia 20%, decreased lymphocytes 17% (grade >=3 13%), potential ICANS 9% (grade >=3 3%)",
        "dose": "Step-up dosing to 90-1,080 micrograms/kg IV weekly, or weekly for 3 weeks then every 3 weeks",
        "price": "No actual or forecast price reported; product remains investigational",
        "price_as_of": "2025-09-01",
        "price_source": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12440289/",
        "price_metric": "forecast_price",
        "price_status": "unavailable",
        "price_classification": "Analyst Assumption",
    },
    {
        "context_ticker": "MOLN",
        "subject": "MP0712 - LCNEC",
        "indication": "DLL3-positive large-cell neuroendocrine carcinoma of lung",
        "comparator": "Obrixtamig in DLL3-positive large-cell neuroendocrine carcinoma",
        "population": "Regimens B2+B3, >=90 micrograms/kg; confirmed-response population (N=9)",
        "as_of_date": "2025-09-01",
        "source_url": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12440289/",
        "source_kind": "peer_reviewed_publication",
        "orr": "44.4% confirmed (4/9)",
        "cr": "0% (0/9)",
        "pr": "44.4% confirmed (4/9)",
        "median_pfs": "Not reported for the LCNEC-L subgroup in the primary publication",
        "median_pfs_status": "unavailable",
        "median_os": "Not reported for the LCNEC-L subgroup in the primary publication",
        "median_os_status": "unavailable",
        "safety": "All-dose safety N=168: treatment-related AE 88%; grade >=3 treatment-related AE 24%; related discontinuation 4%",
        "adverse_events": "Cytokine release syndrome; dysgeusia; pyrexia; asthenia; decreased lymphocyte count; potential ICANS",
        "adverse_event_rates": "CRS 57%, dysgeusia 23%, pyrexia 21%, asthenia 20%, decreased lymphocytes 17% (grade >=3 13%), potential ICANS 9% (grade >=3 3%)",
        "dose": "Step-up dosing to 90-1,080 micrograms/kg IV weekly, or weekly for 3 weeks then every 3 weeks",
        "price": "No actual or forecast price reported; product remains investigational",
        "price_as_of": "2025-09-01",
        "price_source": "https://pmc.ncbi.nlm.nih.gov/articles/PMC12440289/",
        "price_metric": "forecast_price",
        "price_status": "unavailable",
        "price_classification": "Analyst Assumption",
    },
    {
        "context_ticker": "TARA",
        "subject": "TARA-002-NMIBC - NMIBC-BU",
        "indication": "BCG-unresponsive NMIBC with CIS +/- papillary tumors",
        "comparator": "Gemcitabine intravesical system in SunRISe-1",
        "population": "SunRISe-1 Cohort 2 efficacy N=83; safety N=85",
        "as_of_date": "2025-09-09",
        "source_url": "https://www.fda.gov/drugs/resources-information-approved-drugs/fda-approves-gemcitabine-intravesical-system-non-muscle-invasive-bladder-cancer",
        "source_kind": "regulator_clinical_document",
        "orr": "Not reported; ORR was not an efficacy endpoint for CIS NMIBC",
        "orr_status": "unavailable",
        "cr": "82% (95% CI 72%-90%)",
        "pr": "Not applicable/not reported; response endpoint was complete response",
        "pr_status": "unavailable",
        "median_pfs": "Not reported; PFS was not the response endpoint for the SunRISe-1 CIS cohort",
        "median_pfs_status": "unavailable",
        "median_os": "Not reported in the FDA clinical summary for the SunRISe-1 CIS cohort",
        "median_os_status": "unavailable",
        "safety": "Safety N=85: serious adverse reactions 24%, fatal adverse reactions 1.2%, permanent discontinuation 7%",
        "adverse_events": "Urinary frequency; urinary tract infection; dysuria; micturition urgency; urinary tract pain; hematuria",
        "adverse_event_rates": "Urinary frequency 48%, UTI 44% (grade 3/4 6%), dysuria 42%, urgency 34%, urinary tract pain 26% (grade 3/4 7%), hematuria 24% (grade 3/4 2.4%)",
        "dose": "225 mg intravesical system every 3 weeks for 6 months, then every 12 weeks for up to 18 months",
        "clinical_source_overrides": {
            "safety": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219683s000lbl.pdf",
            "adverse_events": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219683s000lbl.pdf",
            "adverse_event_rates": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219683s000lbl.pdf",
            "dose": "https://www.accessdata.fda.gov/drugsatfda_docs/label/2025/219683s000lbl.pdf",
        },
        "price": "USD 67,407.10 cash price per 225 mg intravesical system",
        "price_as_of": "2026-07-18",
        "price_source": "https://www.drugs.com/price-guide/inlexzo",
        "price_metric": "actual_price",
        "price_status": "reported",
        "price_classification": "Market Data",
    },
    {
        "context_ticker": "TARA",
        "subject": "TARA-002-NMIBC - NMIBC-BN",
        "indication": "BCG-naive high-risk NMIBC",
        "comparator": "Sasanlimab plus BCG induction and maintenance in CREST",
        "population": "CREST Arm A N=352; CIS subgroup N=88; safety N=350",
        "as_of_date": "2024-12-02",
        "source_url": "https://www.nature.com/articles/s41591-025-03738-z",
        "source_kind": "peer_reviewed_publication",
        "orr": "Not reported; mixed high-risk NMIBC efficacy was assessed by EFS and CIS complete response",
        "orr_status": "unavailable",
        "cr": "89.8% at any time in the Arm A CIS subgroup",
        "pr": "Not applicable/not reported for NMIBC CIS response assessment",
        "pr_status": "unavailable",
        "median_pfs": "Not reported/not applicable; CREST used event-free survival rather than PFS",
        "median_pfs_status": "unavailable",
        "median_os": "Not reached in any arm at 40.9 months median OS follow-up; Arm A vs Arm C HR 1.13 (95% CI 0.68-1.87)",
        "additional_survival": [
            {
                "metric": "event_free_survival",
                "value": "Median not reached; 36-month EFS 82.1% with sasanlimab plus BCG-I+M vs 74.8% with BCG-I+M; HR 0.68 (95% CI 0.49-0.94)",
                "unit": "% and hazard ratio",
                "status": "reported",
            }
        ],
        "safety": "Arm A safety N=350: treatment-related AE 87.1%; grade >=3 treatment-related AE 29.1%; no treatment-related deaths",
        "adverse_events": "Dysuria; pollakiuria; hematuria; immune-related thyroid disorders; rash; immune-related hepatitis",
        "adverse_event_rates": "Dysuria 29.4%, pollakiuria 22.9%, hematuria 20.9%; any-grade irAE 42.6%, grade >=3 irAE 15.7%; thyroid disorders 17.7%, rash 13.1%, grade 3/4 immune hepatitis 3.4%",
        "dose": "Sasanlimab 300 mg SC every 4 weeks for up to 25 cycles plus intravesical BCG induction and maintenance",
        "price": "No actual or forecast price reported; sasanlimab remains investigational",
        "price_as_of": "2025-05-31",
        "price_source": "https://www.nature.com/articles/s41591-025-03738-z",
        "price_metric": "forecast_price",
        "price_status": "unavailable",
        "price_classification": "Analyst Assumption",
    },
]


def build_facts(group: dict) -> list[dict]:
    common = {
        "subject": group["subject"],
        "indication": group["indication"],
        "comparator": group["comparator"],
        "population": group["population"],
        "as_of_date": group["as_of_date"],
        "source_url": group["source_url"],
        "source_kind": group["source_kind"],
        "classification": "Reported Fact",
    }
    facts = []
    for metric in ("orr", "cr", "pr"):
        facts.append({
            **common,
            "metric_group": "efficacy",
            "metric": metric,
            "value": group[metric],
            "unit": "%",
            "status": group.get(f"{metric}_status", "reported"),
        })
    overrides = group.get("clinical_source_overrides", {})
    for metric in ("median_pfs", "median_os"):
        facts.append({
            **common,
            "metric_group": "survival",
            "metric": metric,
            "value": group[metric],
            "unit": "months",
            "source_url": overrides.get(metric, common["source_url"]),
            "status": group.get(f"{metric}_status", "reported"),
        })
    for row in group.get("additional_survival", []):
        facts.append({
            **common,
            "metric_group": "survival",
            "metric": row["metric"],
            "value": row["value"],
            "unit": row.get("unit"),
            "source_url": row.get("source_url", common["source_url"]),
            "status": row.get("status", "reported"),
        })
    clinical_map = (
        ("safety", "safety", "safety_overview"),
        ("adverse_events", "safety", "adverse_event"),
        ("adverse_event_rates", "safety", "adverse_event_rate"),
        ("dose", "dose", "dose"),
    )
    for key, metric_group, metric in clinical_map:
        facts.append({
            **common,
            "metric_group": metric_group,
            "metric": metric,
            "value": group[key],
            "source_url": overrides.get(key, common["source_url"]),
            "dose": group["dose"] if metric_group == "dose" else None,
            "status": "reported",
        })
    facts.append({
        **common,
        "metric_group": "price",
        "metric": group["price_metric"],
        "value": group["price"],
        "unit": "USD",
        "as_of_date": group["price_as_of"],
        "source_url": group["price_source"],
        "source_kind": "market_data_vendor" if group["price_status"] == "reported" else group["source_kind"],
        "classification": group["price_classification"],
        "status": group["price_status"],
    })
    return facts


def main() -> None:
    totals = {}
    for group in GROUPS:
        ticker = group["context_ticker"]
        stored = upsert_research_facts(build_facts(group), ticker)
        totals[ticker] = totals.get(ticker, 0) + len(stored)
    print("competitor fact backfill:", totals)


if __name__ == "__main__":
    main()
